M48
; DRILL file {KiCad 8.0.2} date 2024-11-11T10:52:25+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-11T10:52:25+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.4Y-2.6575
X3.4Y-3.8386
X6.9Y-2.6575
X6.9Y-3.8386
M30
